"""added likes

Revision ID: efb0cb925e2b
Revises: 2700b4216e02
Create Date: 2022-03-13 13:01:32.733688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb0cb925e2b'
down_revision = '2700b4216e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
